### ISSUE TITLE
MariaDB issue

### ISSUE THREAD

**Issue by ustoopia** [jslsolucoes/nginx-admin#29]
Hi. 
I followed the instructions closely, and the admin-pages connect to the agent fine, but I'm unable to get it to work with MariaDB. I'm not sure if it matters but I noticed that the local database (so not mariadb) was created at this location:  /opt/nginx-admin-2.0.3/opt/nginx-admin-2.0.3/database/nginx_admin.mv.db. So, while troubleshooting I duplicated the database folder so it's also located at /opt/database/nginx_admin.mv.db. I use this java version on a fresh installed Ubuntu 18.04 server:

java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

The full console.log is below.
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by __redirected.__SAXParserFactory (file:/opt/nginx-admin-2.0.3/bin/nginx-admin-ui-standalone-2.0.3-swarm.jar) to constructor com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl()
WARNING: Please consider reporting this to the maintainers of __redirected.__SAXParserFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[0m2018-10-08 21:29:13,347 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                  Logging - STABLE          org.wildfly.swarm:logging:2017.11.0
[0m[0m2018-10-08 21:29:13,431 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:          Bean Validation - STABLE          org.wildfly.swarm:bean-validation:2017.11.0
[0m[0m2018-10-08 21:29:13,432 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:               Management - STABLE          org.wildfly.swarm:management:2017.11.0
[0m[0m2018-10-08 21:29:13,433 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:        CDI Configuration - STABLE          org.wildfly.swarm:cdi-config:2017.11.0
[0m[0m2018-10-08 21:29:13,433 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:              Datasources - STABLE          org.wildfly.swarm:datasources:2017.11.0
[0m[0m2018-10-08 21:29:13,434 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:             Transactions - STABLE          org.wildfly.swarm:transactions:2017.11.0
[0m[0m2018-10-08 21:29:13,435 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                      JCA - STABLE          org.wildfly.swarm:jca:2017.11.0
[0m[0m2018-10-08 21:29:13,435 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                      CDI - STABLE          org.wildfly.swarm:cdi:2017.11.0
[0m[0m2018-10-08 21:29:13,435 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                   JAX-RS - STABLE          org.wildfly.swarm:jaxrs:2017.11.0
[0m[0m2018-10-08 21:29:13,436 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                      JPA - STABLE          org.wildfly.swarm:jpa:2017.11.0
[0m[0m2018-10-08 21:29:13,436 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                 Undertow - STABLE          org.wildfly.swarm:undertow:2017.11.0
[0m[0m2018-10-08 21:29:15,924 INFO  [org.wildfly.swarm.datasources] (main) WFSWARM1003: Auto-detected JDBC driver for mysql
[0m[0m2018-10-08 21:29:15,936 INFO  [org.wildfly.swarm.datasources] (main) WFSWARM1003: Auto-detected JDBC driver for mariadb
[0m[0m2018-10-08 21:29:15,948 INFO  [org.wildfly.swarm.datasources] (main) WFSWARM1003: Auto-detected JDBC driver for sqlserver
[0m[0m2018-10-08 21:29:15,973 INFO  [org.wildfly.swarm.datasources] (main) WFSWARM1003: Auto-detected JDBC driver for postgresql
[0m[0m2018-10-08 21:29:15,983 INFO  [org.wildfly.swarm.datasources] (main) WFSWARM1003: Auto-detected JDBC driver for h2
[0m[0m2018-10-08 21:29:15,998 INFO  [org.wildfly.swarm.datasources] (main) WFSWARM1003: Auto-detected JDBC driver for oracle
[0m[0m2018-10-08 21:29:16,850 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
[0m[0m2018-10-08 21:29:16,940 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0049: WildFly Swarm 2017.11.0 (WildFly Core 2.2.1.Final) starting
[0m[0m2018-10-08 21:29:17,025 INFO  [org.wildfly.swarm] (MSC service thread 1-1) WFSWARM0019: Install MSC service for command line args: [-Dswarm.http.port=4000, -Dswarm.https.port=4443, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dapplication.properties=/opt/nginx-admin-2.0.3/conf/nginx-admin.conf, -Durl.base=http://localhost:4000, -Dmail.server=localhost, -Dmail.port=25, -Dmail.tls=false, -Dmail.from.name=from@localhost.com, -Dmail.from.address=from@localhost.com, -Dmail.authenticate=false, -Dmail.username=xxxx, -Dmail.password=xxxx, -Dmail.charset=utf-8]
[0m21:29:20,071 INFO  [com.jslsolucoes.nginx.admin.database.DatabaseMigrationBuilder] (main) url connection: jdbc:mariadb://localhost:3306/nginx_admin, username: nginx_admin
21:29:20,263 INFO  [com.jslsolucoes.nginx.admin.database.DatabaseMigrationBuilder] (main) Table db_migrate_history already exists in database nginx_admin. Nothing to do.
21:29:20,266 INFO  [com.jslsolucoes.nginx.admin.database.DatabaseMigrationBuilder] (main) Current version is v.0.0.0
21:29:20,293 ERROR [stderr] (main) java.lang.reflect.InvocationTargetException
21:29:20,293 ERROR [stderr] (main) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:29:20,293 ERROR [stderr] (main) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:29:20,293 ERROR [stderr] (main) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:29:20,293 ERROR [stderr] (main) 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
21:29:20,293 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:54)
21:29:20,294 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.run(Main.java:133)
21:29:20,294 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:86)
21:29:20,294 ERROR [stderr] (main) Caused by: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: (conn=199008) Table 'user_sq' already exists
21:29:20,294 ERROR [stderr] (main) 	at com.jslsolucoes.nginx.admin.database.DatabaseMigrationBuilder.migrate(DatabaseMigrationBuilder.java:157)
21:29:20,294 ERROR [stderr] (main) 	at com.jslsolucoes.nginx.admin.ui.standalone.Main.migrateDatabase(Main.java:147)
21:29:20,294 ERROR [stderr] (main) 	at com.jslsolucoes.nginx.admin.ui.standalone.Main.main(Main.java:120)
21:29:20,295 ERROR [stderr] (main) 	... 7 more
21:29:20,297 ERROR [stderr] (main) Caused by: java.sql.SQLSyntaxErrorException: (conn=199008) Table 'user_sq' already exists
21:29:20,298 ERROR [stderr] (main) 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:177)
21:29:20,298 ERROR [stderr] (main) 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
21:29:20,298 ERROR [stderr] (main) 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:228)
21:29:20,299 ERROR [stderr] (main) 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216)
21:29:20,299 ERROR [stderr] (main) 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150)
21:29:20,299 ERROR [stderr] (main) 	at com.jslsolucoes.nginx.admin.database.DatabaseMigrationBuilder.migrate(DatabaseMigrationBuilder.java:146)
21:29:20,300 ERROR [stderr] (main) 	... 9 more
21:29:20,300 ERROR [stderr] (main) Caused by: java.sql.SQLException: Table 'user_sq' already exists
21:29:20,300 ERROR [stderr] (main) Query is: 

21:29:20,300 ERROR [stderr] (main) create table user_sq (

21:29:20,300 ERROR [stderr] (main) 	next_val bigint(10) not null,

21:29:20,305 ERROR [stderr] (main) 	primary key (next_val)

21:29:20,305 ERROR [stderr] (main) )
21:29:20,305 ERROR [stderr] (main) 	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
21:29:20,305 ERROR [stderr] (main) 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:253)
21:29:20,305 ERROR [stderr] (main) 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
21:29:20,305 ERROR [stderr] (main) 	... 11 more
21:29:20,306 ERROR [stderr] (main) Exception in thread "main" java.lang.reflect.InvocationTargetException
21:29:20,306 ERROR [stderr] (main) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:29:20,307 ERROR [stderr] (main) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:29:20,307 ERROR [stderr] (main) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:29:20,307 ERROR [stderr] (main) 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
21:29:20,307 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:54)
21:29:20,308 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.run(Main.java:133)
21:29:20,308 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:86)
21:29:20,308 ERROR [stderr] (main) Caused by: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: (conn=199008) Table 'user_sq' already exists
21:29:20,308 ERROR [stderr] (main) 	at com.jslsolucoes.nginx.admin.database.DatabaseMigrationBuilder.migrate(DatabaseMigrationBuilder.java:157)
21:29:20,309 ERROR [stderr] (main) 	at com.jslsolucoes.nginx.admin.ui.standalone.Main.migrateDatabase(Main.java:147)
21:29:20,309 ERROR [stderr] (main) 	at com.jslsolucoes.nginx.admin.ui.standalone.Main.main(Main.java:120)
21:29:20,309 ERROR [stderr] (main) 	... 7 more
21:29:20,310 ERROR [stderr] (main) Caused by: java.sql.SQLSyntaxErrorException: (conn=199008) Table 'user_sq' already exists
21:29:20,310 ERROR [stderr] (main) 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:177)
21:29:20,310 ERROR [stderr] (main) 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
21:29:20,310 ERROR [stderr] (main) 	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:228)
21:29:20,310 ERROR [stderr] (main) 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216)
21:29:20,310 ERROR [stderr] (main) 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150)
21:29:20,311 ERROR [stderr] (main) 	at com.jslsolucoes.nginx.admin.database.DatabaseMigrationBuilder.migrate(DatabaseMigrationBuilder.java:146)
21:29:20,311 ERROR [stderr] (main) 	... 9 more
21:29:20,312 ERROR [stderr] (main) Caused by: java.sql.SQLException: Table 'user_sq' already exists
21:29:20,312 ERROR [stderr] (main) Query is: 

21:29:20,312 ERROR [stderr] (main) create table user_sq (

21:29:20,312 ERROR [stderr] (main) 	next_val bigint(10) not null,

21:29:20,312 ERROR [stderr] (main) 	primary key (next_val)

21:29:20,312 ERROR [stderr] (main) )
21:29:20,312 ERROR [stderr] (main) 	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
21:29:20,312 ERROR [stderr] (main) 	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:253)
21:29:20,312 ERROR [stderr] (main) 	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
21:29:20,313 ERROR [stderr] (main) 	... 11 more
```
I checked the database and noticed it has been filled with several tables. I installed java 8 (openjdk-8-jdk) and changed the default version of java to 8 (update-alternatives --config java) and tried to run it but the error log shows the exact same errors as posted above. 

Any idea how I can resolve this?
Thanks!

**Comment by iqpkeq** [comment]
the New Issue:
Mariadb 5.5  Centos7.0
**start the nginx-admin,Bug report:**
`java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:54)
	at org.wildfly.swarm.bootstrap.Main.run(Main.java:133)
	at org.wildfly.swarm.bootstrap.Main.main(Main.java:86)
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.jslsolucoes.nginx.admin.ui.config.ConfigurationLoader.databasePool(ConfigurationLoader.java:86)
	at com.jslsolucoes.nginx.admin.ui.config.ConfigurationLoader.database(ConfigurationLoader.java:80)
	at com.jslsolucoes.nginx.admin.ui.config.ConfigurationLoader.build(ConfigurationLoader.java:31)
	at com.jslsolucoes.nginx.admin.ui.standalone.Main.main(Main.java:43)
	... 7 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:54)
	at org.wildfly.swarm.bootstrap.Main.run(Main.java:133)
	at org.wildfly.swarm.bootstrap.Main.main(Main.java:86)
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.jslsolucoes.nginx.admin.ui.config.ConfigurationLoader.databasePool(ConfigurationLoader.java:86)
	at com.jslsolucoes.nginx.admin.ui.config.ConfigurationLoader.database(ConfigurationLoader.java:80)
	at com.jslsolucoes.nginx.admin.ui.config.ConfigurationLoader.build(ConfigurationLoader.java:31)
	at com.jslsolucoes.nginx.admin.ui.standalone.Main.main(Main.java:43)
	... 7 more
`

**the nginx-admin.conf file:**
`NGINX_ADMIN_DB_DRIVER=mariadb
 NGINX_ADMIN_DB_HOST=localhost
 NGINX_ADMIN_DB_PORT=3306
 NGINX_ADMIN_DB_NAME=nginx_admin
 NGINX_ADMIN_DB_USERNAME=nginx_admin
 NGINX_ADMIN_DB_PASSWORD=1234
`
