### ISSUE TITLE
Error 500 after import certificate ssl 

### ISSUE THREAD

**Issue by idurbgt** [jslsolucoes/nginx-admin#3]
Hello,

i had error 500 after import ssl certificate. Please take a look error log bellow :

Stack trace :
javax.servlet.ServletException: /WEB-INF/jsp/sslCertificate/list.jsp raised an exception
at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:127)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)

Thank you

**Comment by jslsolucoes** [comment]
Hi, thanks for reporting we will check for this error. Can you please post the complete stack trace of error or the content of file available in /opt/nginx-admin/log/

**Comment by idurbgt** [comment]
Hi, sorry for late response,

here is log content /opt/nginx-admin/log/console.log :
09:12:16,121 ERROR [io.undertow.request] (default task-102) UT005023: Exception handling request to /WEB-INF/jsp/sslCertificate/list.jsp: javax.servlet.ServletException: /WEB-INF/jsp/sslCertificate/list.jsp raised an exception
        at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:127)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:62)
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.el.PropertyNotFoundException: The class 'com.jslsolucoes.nginx.admin.model.SslCertificate' does not have the property 'certificate'.
        at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:886)
        at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:818)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp._jspService(list_jsp.java:121)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:433)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:402)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:346)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at br.com.caelum.vraptor.core.DefaultStaticContentHandler.deferProcessingToContainer(DefaultStaticContentHandler.java:87)
        at br.com.caelum.vraptor.core.DefaultStaticContentHandler$Proxy$_$$_WeldClientProxy.deferProcessingToContainer(Unknown Source)
        at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:114)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.jsp.JspFileHandler.handleRequest(JspFileHandler.java:32)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:62)
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:274)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:209)
        at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImpl(RequestDispatcherImpl.java:221)
        at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImplSetup(RequestDispatcherImpl.java:147)
        at io.undertow.servlet.spec.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:111)
        at br.com.caelum.vraptor.view.DefaultPageResult.defaultView(DefaultPageResult.java:81)
        at br.com.caelum.vraptor.observer.ForwardToDefaultView.forward(ForwardToDefaultView.java:67)
        at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:313)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:291)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:269)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:302)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:291)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:89)
        at br.com.caelum.vraptor.observer.RequestHandlerObserver.handle(RequestHandlerObserver.java:94)
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:313)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:291)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:269)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:302)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:291)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:89)
        at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:123)
        ... 41 more
Caused by: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.el.PropertyNotFoundException: The class 'com.jslsolucoes.nginx.admin.model.SslCertificate' does not have the property 'certificate'.
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp$Helper.invoke(list_jsp.java:713)
        at com.jslsolucoes.tagria.lib.util.TagUtil.getBody(TagUtil.java:174)
        at com.jslsolucoes.tagria.lib.tag.html.BlockTag.doTag(BlockTag.java:42)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp._jspx_meth_html_005fblock_005f1(list_jsp.java:190)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp.access$1(list_jsp.java:180)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp$Helper.invoke0(list_jsp.java:518)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp$Helper.invoke(list_jsp.java:675)
        at com.jslsolucoes.tagria.lib.util.TagUtil.getBody(TagUtil.java:174)
        at com.jslsolucoes.tagria.lib.tag.html.ViewTag.doTag(ViewTag.java:112)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp._jspx_meth_html_005fview_005f0(list_jsp.java:140)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp._jspService(list_jsp.java:108)
        ... 96 more
Caused by: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.el.PropertyNotFoundException: The class 'com.jslsolucoes.nginx.admin.model.SslCertificate' does not have the property 'certificate'.
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp$Helper.invoke(list_jsp.java:713)
        at com.jslsolucoes.tagria.lib.util.TagUtil.getBody(TagUtil.java:174)
        at com.jslsolucoes.tagria.lib.tag.html.GridTag.doTag(GridTag.java:208)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp._jspx_meth_html_005fgrid_005f0(list_jsp.java:213)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp.access$3(list_jsp.java:195)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp$Helper.invoke2(list_jsp.java:542)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp$Helper.invoke(list_jsp.java:681)
        ... 106 more
Caused by: javax.servlet.jsp.JspException: javax.el.PropertyNotFoundException: The class 'com.jslsolucoes.nginx.admin.model.SslCertificate' does not have the property 'certificate'.
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp$Helper.invoke(list_jsp.java:713)
        at com.jslsolucoes.tagria.lib.util.TagUtil.getBody(TagUtil.java:174)
        at com.jslsolucoes.tagria.lib.tag.html.GridColumnTag.doTag(GridColumnTag.java:48)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp._jspx_meth_html_005fgridColumn_005f1(list_jsp.java:249)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp.access$5(list_jsp.java:237)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp$Helper.invoke3(list_jsp.java:557)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp$Helper.invoke(list_jsp.java:684)
        ... 112 more
Caused by: javax.el.PropertyNotFoundException: The class 'com.jslsolucoes.nginx.admin.model.SslCertificate' does not have the property 'certificate'.
        at javax.el.BeanELResolver.getBeanProperty(BeanELResolver.java:568)
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:229)
        at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:110)
        at com.sun.el.parser.AstValue.getValue(AstValue.java:139)
        at com.sun.el.parser.AstValue.getValue(AstValue.java:203)
        at com.sun.el.parser.AstDynamicExpression.getValue(AstDynamicExpression.java:63)
        at com.sun.el.parser.AstCompositeExpression.getValue(AstCompositeExpression.java:68)
        at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
        at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
        at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:917)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp._jspx_meth_html_005flink_005f0(list_jsp.java:266)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp.access$9(list_jsp.java:254)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp$Helper.invoke5(list_jsp.java:592)
        at org.apache.jsp.WEB_002dINF.jsp.sslCertificate.list_jsp$Helper.invoke(list_jsp.java:690)
        ... 118 more

**Comment by jslsolucoes** [comment]
Bug fix added to develop branch. Will release correction on next release. Thanks for contrib
